logging:
  level:
    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expensestracker
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    clean-on-validation-error: true

  logging:
    level:
      org.flywaydb: DEBUG
